<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/mrm</project>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/mspsim</project>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/avrora</project>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/serial_socket</project>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/collect-view</project>
  <project EXPORT="discard">[CONTIKI_DIR]/tools/cooja/apps/powertracker</project>
  <simulation>
    <title>Wormhole attack</title>
    <delaytime>-2147483648</delaytime>
    <randomseed>123456</randomseed>
    <motedelay_us>1000000</motedelay_us>
    <radiomedium>
      se.sics.cooja.radiomediums.DirectedGraphMedium
      <edge>
        <source>1</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>8</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>1</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>24</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>1</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>25</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>2</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>9</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>2</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>13</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>3</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>19</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>3</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>4</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>11</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>4</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>25</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>5</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>7</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>5</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>15</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>5</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>20</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>6</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>8</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>7</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>5</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>7</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>20</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>8</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>1</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>8</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>6</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>8</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>19</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>9</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>2</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>9</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>13</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>9</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>17</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>9</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>22</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>9</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>10</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>3</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>10</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>12</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>10</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>18</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>10</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>19</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>10</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>11</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>4</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>11</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>8</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>11</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>15</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>12</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>3</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>12</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>10</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>12</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>20</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>12</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>12</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>13</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>16</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>13</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>17</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>14</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>16</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>15</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>5</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>15</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>11</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>15</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>18</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>16</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>13</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>16</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>14</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>17</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>9</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>17</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>13</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>17</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>17</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>18</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>10</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>18</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>11</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>18</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>15</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>18</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>25</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>19</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>3</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>19</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>4</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>19</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>10</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>19</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>20</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>5</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>20</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>7</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>20</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>12</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>20</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>22</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>20</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>21</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>3</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>21</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>10</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>21</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>12</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>21</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>17</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>21</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>22</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>7</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>22</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>23</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>9</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>12</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>17</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>20</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>21</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>23</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>22</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>24</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>1</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>24</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>10</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>24</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>19</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>24</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>25</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>1</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>4</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>11</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>18</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>24</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>2</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>25</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
      <edge>
        <source>25</source>
        <dest>
          se.sics.cooja.radiomediums.DGRMDestinationRadio
          <radio>2</radio>
          <ratio>1.0</ratio>
          <signal>-10.0</signal>
          <delay>0</delay>
        </dest>
      </edge>
    </radiomedium>
    <events>
      <logoutput>40000</logoutput>
    </events>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>sky1</identifier>
      <description>Sky Sink</description>
      <source EXPORT="discard">[CONTIKI_DIR]/examples/ipv6/rpl-collect/udp-sink.c</source>
      <commands EXPORT="discard">make udp-sink.sky TARGET=sky</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]/examples/ipv6/rpl-collect/udp-sink.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <motetype>
      se.sics.cooja.motes.DisturberMoteType
      <identifier>apptype1</identifier>
      <description>Disturber Mote Type #apptype1</description>
    </motetype>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>sky2</identifier>
      <description>Sky Collect</description>
      <source EXPORT="discard">[CONTIKI_DIR]/examples/ipv6/rpl-collect/udp-sender.c</source>
      <commands EXPORT="discard">make udp-sender.sky TARGET=sky</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]/examples/ipv6/rpl-collect/udp-sender.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>sky3</identifier>
      <description>Evil sky</description>
      <source EXPORT="discard">[CONTIKI_DIR]-evil/examples/ipv6/rpl-collect/udp-sender.c</source>
      <commands EXPORT="discard">make udp-sender.sky TARGET=sky</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]-evil/examples/ipv6/rpl-collect/udp-sender.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>43.810697953656295</x>
        <y>-8.214317653341729</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>1</id>
      </interface_config>
      <motetype_identifier>sky1</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>75.3045202612029</x>
        <y>96.00545086902731</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>2</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>63.02123102238879</x>
        <y>36.05194919506978</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>3</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>-14.288350564072202</x>
        <y>5.6947836506479215</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>4</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>2.2792792440593024</x>
        <y>67.20496475511567</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>5</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>99.07568195238203</x>
        <y>7.099269393178131</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>6</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>0.27735043855445785</x>
        <y>94.13426051875796</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>7</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>80.56796440389965</x>
        <y>6.194053230066099</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>8</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>62.135405058322874</x>
        <y>84.88268066917279</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>9</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>32.0569221670785</x>
        <y>28.159086153520096</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>10</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>-17.25924887147751</x>
        <y>37.74210489835381</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>11</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>31.02821653465918</x>
        <y>58.45739586663132</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>12</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>85.0854222099058</x>
        <y>67.20496475511567</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>13</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>89.73745271360504</x>
        <y>36.50156343070068</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>14</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>-7.024781763339179</x>
        <y>56.040091546237484</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>15</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>99.18263032502867</x>
        <y>54.869000227276565</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>16</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>63.22330056292914</x>
        <y>65.70567455143525</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>17</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>11.911722605391494</x>
        <y>36.4050386994556</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>18</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>54.26059284050583</x>
        <y>22.375951828803807</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>19</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>23.8363835329531</x>
        <y>69.28006792783084</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>20</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>46.62836162840099</x>
        <y>47.385290998320606</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>21</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>32.990465603974094</x>
        <y>96.10394212658065</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>22</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>39.80565864056652</x>
        <y>72.78740135955475</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>23</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>32.982680568474294</x>
        <y>12.000869444551338</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>24</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>4.335914209025782</x>
        <y>11.883941256099728</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        se.sics.cooja.mspmote.interfaces.MspMoteID
        <id>25</id>
      </interface_config>
      <motetype_identifier>sky2</motetype_identifier>
    </mote>
  </simulation>
  <plugin>
    se.sics.cooja.plugins.Visualizer
    <plugin_config>
      <skin>se.sics.cooja.plugins.skins.IDVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.MoteTypeVisualizerSkin</skin>
      <viewport>9.908489326959637 0.0 0.0 9.908489326959637 544.1315246195226 132.57329697821075</viewport>
      <hidden />
    </plugin_config>
    <width>1910</width>
    <z>0</z>
    <height>1147</height>
    <location_x>0</location_x>
    <location_y>0</location_y>
  </plugin>
</simconf>

